<a href="https://colab.research.google.com/github/gongboogi/Python-Practice/blob/main/Numpy_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 넘파이 기초 연습하기

넘파이 임포트

In [2]:
# 넘파이 라이브러리 임포트
import numpy as np

# 소수점 세 번째 자리가지 표시
%precision 3

'%.3f'

배열 생성과 조작, 가공

In [3]:
# 배열 생성
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

데이터 형

In [4]:
data.dtype

dtype('int64')

In [6]:
type(data)

numpy.ndarray

차원과 원소 수: ndim, size

In [8]:
print('차원수:', data.ndim)
print('원소수', data.size )

차원수: 1
원소수 10


모든 원소에 대한 계산

In [18]:
# 각 원소를 두 배로 증가시키기
data * 2

array([18,  4,  6,  8, 20, 12, 14, 16,  2, 10])

In [23]:
# 각 원소의 각 연산
data1 = np.array([1,2,3,4,5,6,7,8,9,10])
data2 = np.array([10,9,8,7,6,5,4,3,2,1])
print('곱셈', data1 * data2)
print('거듭제곱', data1 **2)
print('나눗셈', data1 / data2)

곱셈 [10 18 24 28 30 30 28 24 18 10]
거듭제곱 [  1   4   9  16  25  36  49  64  81 100]
나눗셈 [ 0.1    0.222  0.375  0.571  0.833  1.2    1.75   2.667  4.5   10.   ]


정렬(sort)

기본설정: 오름차순

In [28]:
# 현재 값을 그대로 표시
print('현재 순서', data)

# 정렬한 결과 표시
data.sort()
print('오름차순 정렬 후', data)

현재 순서 [10  9  8  7  6  5  4  3  2  1]
오름차순 정렬 후 [ 1  2  3  4  5  6  7  8  9 10]


In [29]:
#내림차순
data[::-1].sort()
print('내림차순 정렬 후', data)

내림차순 정렬 후 [10  9  8  7  6  5  4  3  2  1]


최소, 최대, 합계, 누적합 계산

In [35]:
print("data: ",data)
print("Min: ", data.min())
print("Max: ", data.max())
print("Sum: ", data.sum())
print("Cum: ", data.cumsum())
print("Ratio: ", data.cumsum() / data.sum())

data:  [10  9  8  7  6  5  4  3  2  1]
Min:  1
Max:  10
Sum:  55
Cum:  [10 19 27 34 40 45 49 52 54 55]
Ratio:  [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]


난수

In [36]:
import numpy.random as random

In [37]:
# 난수 시드
random.seed(0)

# 정규분포(평균0, 분산1)를 따르는 난수 10개 발생
rnd_data = random.randn(10)

print('10개의 난수 배열', rnd_data)

10개의 난수 배열 [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


데이터 무작위 추출: random.chice

In [41]:
# 추출 대상 데이터
data = np.array([9,2,3,4,10,6,7,8,1,5])

# 무작위 추출
# 10개의 값을 추출( 중복이 있는 복원 추출)
print(random.choice(data,10))

# 10개의 앖을 추출(중복이 없는 비복원 추출)
print(random.choice(data, 10, replace = False))

[ 4  3  8  3  9  9 10  6  6  7]
[ 4  6  9  7  3  8  5  2 10  1]


행렬

In [44]:
np.arange(9) #arange(): 지정한 숫자까지의 연속된 정수 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
array1 = np.arange(9).reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [58]:
# 첫 번째 행
array1[0,:]

array([0, 1, 2])

In [57]:
# 첫 번째 열
array1[:,0]

array([0, 3, 6])

행렬 연산

In [59]:
array2 = np.arange(9,18).reshape(3,3)
print(array2)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [60]:
# 행렬 곱셈: dot
np.dot(array1, array2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [61]:
# 각 원소 간의 곱
array1 * array2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

원소가 0이나 1인 행렬 생성

In [69]:
# np.zeros(): 모든 원소가 0인 행렬 생성
# np.ones(): 모든 원소가 1인 행렬 생성

print(np.zeros((2, 3), dtype = np.int64))
print(np.ones((2, 3), dtype = np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]




---



Q. 1부터 50까지의 자연수의 합을 계산하고 계산 결과를 출력하는 프로그램을 작성하세요. 단, np.array로 1부터 50까지 숫자의 배열을 만들고 총합을 구하는 방식으로 계산하세요.

In [78]:
# 1
q1 = np.arange(1,51)
q1 = np.array(q1)
print(q1)

print('합: ', q1.sum())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
합:  1275


In [88]:
#2
q1 = np.array([i for i in  range(1, 51)])
print(q1)
q1_sum = q1.sum()
print('합: ', q1_sum)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
합:  1275


Q2. 표준정규분포를 따르는 10개의 난수를 발생시켜 배열을 생성해라. 또한 배열의 최솟값과 최댓값, 합계를 구하는 프로그램을 작성하시오.



In [103]:
#1
random.seed(0)
q2 = random.randn(10)
print('최솟값: ', q2.min())
print('최댓값: ', q2.max())
print('합계: ', q2.sum()) 

최솟값:  -0.977277879876411
최댓값:  2.240893199201458
합계:  7.380231707288347
