<a href="https://colab.research.google.com/github/gongboogi/Python-Practice/blob/main/SciPy_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 사이파이 기초

1. 사이파이 라이브러리 임포트

In [2]:
# 사이파이 라이브러리 임포트
import numpy as np
import scipy as sp

# 선형대수용 라이브러리, 최적화 계산(최솟값)용 함수
import scipy.linalg as linalg
from scipy.optimize import minimize_scalar

2. 행렬 연산: det

In [3]:
matrix = np.array([[1,-1,-1], [-1,1,-1], [-1,-1,1]])

# 행렬식
print('행렬식: ', linalg.det(matrix))

행렬식:  -4.0


In [5]:
# 역행렬: inv
print('역행렬')
print(linalg.inv(matrix))

역행렬
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


In [6]:
print(matrix.dot(linalg.inv(matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


고윳값과 고유벡터

In [8]:
# 고윳값과 고유벡터: linalg의 eig 함수
eig_value, eig_vector = linalg.eig(matrix)

print('고윳값')
print(eig_value)
print('고유벡터')
print(eig_vector)

고윳값
[-1.+0.j  2.+0.j  2.+0.j]
고유벡터
[[ 0.57735027  0.81649658  0.40824829]
 [ 0.57735027 -0.40824829 -0.81649658]
 [ 0.57735027 -0.40824829  0.40824829]]


## 뉴턴법

최적화 계산에 대해서

**방정식의 해 구하기**

In [9]:
# 함수 정의
def my_function(x) :
  return (x**2 + 2*x + 1)

예시 코드에서 f(x) = 0의 해를 구하기 위해서 newton 함수를 사용한다.

newton 함수의 첫 번째 인수로 my_function 함수를 설정하고, 두 번째 인수는 해를 결정하는 조건식인 f(x) = 0에서 함수의 값 0을 지정한다.

In [10]:
# 뉴턴법 임포트
from scipy.optimize import newton

# 연산 실행
print(newton(my_function, 0))

-0.9999999852953906




---



### 연습문제

1. 다음 행렬에 대해 행렬식을 구하세요.